// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TCCwNADYyr4eYoP5Jb3DqZqBOHzr59Q',
    appId: '1:637699546635:web:f5a5fc67d336395b05f10e',
    messagingSenderId: '637699546635',
    projectId: 'soccerdle',
    authDomain: 'soccerdle.firebaseapp.com',
    storageBucket: 'soccerdle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQOeASIDkGhwfwSabvywNmlsJQ_wtcns',
    appId: '1:637699546635:android:5d98f97759e4ac2005f10e',
    messagingSenderId: '637699546635',
    projectId: 'soccerdle',
    storageBucket: 'soccerdle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr99jcDLBFwIvkMNI_J8H2QEyJgy76BBI',
    appId: '1:637699546635:ios:c79c85a00cb5413e05f10e',
    messagingSenderId: '637699546635',
    projectId: 'soccerdle',
    storageBucket: 'soccerdle.appspot.com',
    iosBundleId: 'com.example.soccerdle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr99jcDLBFwIvkMNI_J8H2QEyJgy76BBI',
    appId: '1:637699546635:ios:c79c85a00cb5413e05f10e',
    messagingSenderId: '637699546635',
    projectId: 'soccerdle',
    storageBucket: 'soccerdle.appspot.com',
    iosBundleId: 'com.example.soccerdle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5TCCwNADYyr4eYoP5Jb3DqZqBOHzr59Q',
    appId: '1:637699546635:web:7c93935220bf720b05f10e',
    messagingSenderId: '637699546635',
    projectId: 'soccerdle',
    authDomain: 'soccerdle.firebaseapp.com',
    storageBucket: 'soccerdle.appspot.com',
  );

}